# Generated by Django 5.1 on 2024-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AndroidMetadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("locale", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "android_metadata",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("title", models.TextField(primary_key=True, serialize=False)),
                ("colorid", models.IntegerField(db_column="colorId")),
                ("order", models.IntegerField()),
                ("archived", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": "Label",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("durationwork", models.IntegerField(db_column="durationWork")),
                ("durationbreak", models.IntegerField(db_column="durationBreak")),
                ("enablelongbreak", models.IntegerField(db_column="enableLongBreak")),
                (
                    "durationlongbreak",
                    models.IntegerField(db_column="durationLongBreak"),
                ),
                (
                    "sessionsbeforelongbreak",
                    models.IntegerField(db_column="sessionsBeforeLongBreak"),
                ),
            ],
            options={
                "db_table": "Profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoomMasterTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("identity_hash", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "room_master_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.IntegerField()),
                ("duration", models.IntegerField()),
            ],
            options={
                "db_table": "Session",
                "managed": False,
            },
        ),
    ]
